### ISSUE TITLE
Visualize training process and output learning statistics

### ISSUE THREAD

**Issue by xubo92** [amolchanov86/quad_sim2multireal#1]
Hi @amolchanov86 ,

Thanks a lot for your great work! It's amazing performance simply using model-free RL policy transfer.

I'm running your code right now and wondering if there is any way to visualize the simulation and print the training information, like reward, episode number, etc.

Thank you!

Best,
Xubo

**Comment by TaoChenOSU** [comment]
Hello,

You could use Tensorboard for monitoring purposes.

Best, 
Tao
